# -*- coding: utf-8 -*-
# Cybersecurity-Mastery - an interactive, offline cybersecurity learning app.
# Copyright (C) 2026 Nithees Narendra S
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of Cybersecurity-Mastery. It is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. There is NO WARRANTY. See the
# LICENSE file for the full text. For use outside the GPL-3.0 terms (e.g.
# proprietary/commercial), contact the copyright holder for a separate licence.

"""Topic manifest, part 2: sections 06-15 (offensive through compliance)."""

SECTIONS = [
    {
        "id": "06-offensive-security",
        "title": "Offensive Security",
        "desc": "The attacker's methodology end to end, structured on the cyber kill chain and "
                "MITRE ATT&CK. Every technique is paired with a lawful, local lab.",
        "chapters": [
            ("offensive-methodology", "Offensive Security Methodology", "beginner", 6,
             "Kill chain, ATT&CK, PTES and how engagements, scoping and rules of engagement are structured."),
            ("recon", "Reconnaissance", "beginner", 10,
             "Passive and active information gathering, footprinting and building a target model."),
            ("osint", "OSINT", "beginner", 10,
             "People, infrastructure and metadata discovery from open sources with a clean audit trail."),
            ("enumeration", "Enumeration", "intermediate", 12,
             "Service, user, share and application enumeration that turns access into a foothold plan."),
            ("scanning", "Scanning", "beginner", 10,
             "Host discovery, port and service scanning, versioning and safe scan tuning."),
            ("vulnerability-assessment", "Vulnerability Assessment", "intermediate", 8,
             "Scanner selection, validation, false-positive triage and risk-based prioritisation."),
            ("exploitation", "Exploitation", "advanced", 14,
             "Turning a vulnerability into reliable access, payload selection and staging in a lab."),
            ("password-attacks", "Password Attacks", "intermediate", 10,
             "Guessing, spraying, cracking, and coercion, plus defensive lockout and detection."),
            ("persistence", "Persistence", "advanced", 12,
             "Maintaining access across reboots on Linux and Windows and the telemetry it generates."),
            ("privilege-escalation", "Privilege Escalation", "advanced", 14,
             "Local escalation on Linux and Windows through misconfiguration, tokens and kernel bugs."),
            ("lateral-movement", "Lateral Movement", "advanced", 12,
             "Moving between hosts with remote execution, pivoting and relayed credentials."),
            ("defense-evasion", "Defense Evasion", "advanced", 12,
             "Bypassing controls, obfuscation, and living-off-the-land, with the detections they trip."),
            ("credential-access", "Credential Access", "advanced", 12,
             "Dumping, sniffing and forging credentials across the OS and directory services."),
            ("command-and-control", "Command and Control", "advanced", 10,
             "C2 architecture, channels, redirectors, malleable profiles and beacon detection."),
            ("exfiltration", "Exfiltration", "advanced", 8,
             "Staging, compression, encryption and covert channels, plus DLP and egress detection."),
            ("post-exploitation", "Post-Exploitation", "advanced", 12,
             "Situational awareness, data collection, objective completion and cleanup discipline."),
            ("active-directory-attacks", "Active Directory Attacks", "expert", 18,
             "Kerberoasting, delegation abuse, ACL attacks, DCSync and full domain-compromise chains."),
            ("wireless-attacks", "Wireless Attacks", "advanced", 10,
             "Capturing handshakes, evil twins and PMKID attacks against a lab access point."),
            ("social-engineering", "Social Engineering", "intermediate", 8,
             "Pretexting, phishing infrastructure, payload delivery and human-layer defences."),
            ("red-team", "Red Teaming", "expert", 14,
             "Objective-based adversary emulation, infrastructure, OPSEC and reporting."),
            ("opsec", "Operational Security", "advanced", 8,
             "Attribution management, infrastructure hygiene and separating tooling from identity."),
            ("ctf", "Capture The Flag", "beginner", 10,
             "Categories, methodology, tooling and a structured path from first blood to expert."),
            ("bug-bounty", "Bug Bounty", "intermediate", 10,
             "Program selection, scope, recon automation, reporting and building a repeatable pipeline."),
            ("exploit-development", "Exploit Development", "expert", 18,
             "From crash to control: fuzzing, triage, primitive building and mitigation bypass."),
        ],
    },
    {
        "id": "07-defensive-security",
        "title": "Defensive Security",
        "desc": "Building, running and improving the blue team: telemetry, detection, response and hunting.",
        "chapters": [
            ("defensive-methodology", "Defensive Security Methodology", "beginner", 6,
             "Defence in depth, the SOC operating model, detection maturity and the OODA loop."),
            ("soc", "Security Operations Center", "beginner", 10,
             "Tiers, roles, runbooks, metrics, shift handover and alert-fatigue management."),
            ("siem", "SIEM", "intermediate", 12,
             "Log pipelines, normalisation, correlation, use-case development and content tuning."),
            ("ids", "Intrusion Detection Systems", "intermediate", 8,
             "Signature vs anomaly detection, sensor placement, tuning and evasion awareness."),
            ("ips", "Intrusion Prevention Systems", "intermediate", 6,
             "Inline enforcement, fail-open/closed, false-positive risk and change control."),
            ("edr", "Endpoint Detection and Response", "advanced", 12,
             "Sensor telemetry, behavioural detection, response actions and tamper resistance."),
            ("xdr", "Extended Detection and Response", "intermediate", 6,
             "Cross-domain correlation, data fabric design and the promise and limits of XDR."),
            ("threat-hunting", "Threat Hunting", "advanced", 12,
             "Hypothesis-driven hunts, the pyramid of pain, MITRE-aligned queries and hunt reporting."),
            ("threat-intelligence", "Threat Intelligence", "intermediate", 10,
             "Intel lifecycle, strategic/operational/tactical intel, feeds and the diamond model."),
            ("incident-response", "Incident Response", "advanced", 14,
             "PICERL lifecycle, containment strategy, evidence handling and post-incident review."),
            ("detection-engineering", "Detection Engineering", "advanced", 14,
             "Detection as code, the detection lifecycle, testing, and reducing false positives."),
            ("log-analysis", "Log Analysis", "intermediate", 10,
             "Sources, parsing, enrichment, and pivoting across logs to reconstruct activity."),
            ("digital-forensics-intro", "Digital Forensics Fundamentals", "intermediate", 10,
             "Order of volatility, chain of custody, imaging and forensic soundness."),
            ("memory-forensics", "Memory Forensics", "advanced", 12,
             "Acquisition, Volatility 3 workflows, process/handle analysis and malware in RAM."),
            ("disk-forensics", "Disk Forensics", "advanced", 12,
             "File systems, deleted-file recovery, timelines, artefacts and carving."),
            ("email-analysis", "Email Analysis", "intermediate", 6,
             "Header forensics, authentication results, phishing triage and attachment handling."),
            ("network-forensics", "Network Forensics", "advanced", 10,
             "Full-packet and flow analysis, protocol reconstruction and beacon detection."),
            ("yara", "YARA", "intermediate", 8,
             "Rule syntax, strings and conditions, performance, and building a maintainable ruleset."),
            ("sigma", "Sigma", "intermediate", 8,
             "Generic detection rules, the taxonomy, backends and converting to SIEM queries."),
            ("purple-teaming", "Purple Teaming", "advanced", 8,
             "Adversary emulation with Atomic Red Team, detection validation and feedback loops."),
            ("security-monitoring", "Security Monitoring Architecture", "intermediate", 8,
             "Visibility mapping, log source coverage, retention and the MITRE DeTT&CT approach."),
            ("vulnerability-management", "Vulnerability Management", "intermediate", 10,
             "Asset inventory, scanning cadence, risk scoring, SLAs and remediation workflows."),
        ],
    },
    {
        "id": "08-malware",
        "title": "Malware Analysis",
        "desc": "What malware is, how each family behaves, and how to analyse it safely in isolation. "
                "All analysis is performed on inert samples in a disposable lab.",
        "chapters": [
            ("malware-fundamentals", "Malware Fundamentals", "beginner", 8,
             "Classification, the malware lifecycle, delivery, and building a safe analysis lab."),
            ("virus", "Viruses", "beginner", 5,
             "Infection strategies, file/boot/macro viruses and why self-replication defines the class."),
            ("worm", "Worms", "beginner", 5,
             "Self-propagation, exploitation of network services and historic internet-scale outbreaks."),
            ("trojan", "Trojans", "beginner", 5,
             "Social-engineering delivery, RATs, bankers and payload staging."),
            ("spyware", "Spyware and Stalkerware", "beginner", 5,
             "Data collection techniques, keylogging, surveillance implants and detection."),
            ("rootkit", "Rootkits", "advanced", 10,
             "User-mode vs kernel-mode hooking, DKOM, hiding techniques and rootkit detection."),
            ("bootkit", "Bootkits", "expert", 10,
             "MBR/VBR and UEFI implants, Secure Boot bypass and firmware-level persistence."),
            ("ransomware", "Ransomware", "advanced", 10,
             "Encryption schemes, double extortion, RaaS economics and containment/response."),
            ("botnet", "Botnets", "intermediate", 8,
             "C2 topologies, DGA, fast flux, takedowns and sinkholing."),
            ("loaders", "Loaders and Droppers", "advanced", 8,
             "Multi-stage delivery, payload decryption, injection and loader-as-a-service."),
            ("crypters", "Crypters, Packers and Obfuscation", "advanced", 10,
             "Packing, polymorphism, anti-analysis and generic unpacking methodology."),
            ("fileless-malware", "Fileless Malware", "advanced", 10,
             "Living-off-the-land, in-memory execution, WMI/registry persistence and detection gaps."),
            ("reverse-engineering", "Reverse Engineering", "expert", 18,
             "Disassembly, decompilation, control-flow recovery and a full RE workflow."),
            ("static-analysis", "Static Analysis", "intermediate", 10,
             "Triage, strings, imports, PE/ELF structure, YARA and safe first-look techniques."),
            ("dynamic-analysis", "Dynamic Analysis", "advanced", 12,
             "Behavioural monitoring, API tracing, network capture and controlled detonation."),
            ("sandboxing", "Sandboxing", "intermediate", 8,
             "Automated analysis environments, evasion, instrumentation and report interpretation."),
            ("shellcode-analysis", "Shellcode Analysis", "advanced", 10,
             "Position-independent code, encoders, emulation with sctest/speakeasy and decoding stubs."),
            ("anti-analysis", "Anti-Analysis and Evasion", "expert", 10,
             "Anti-debug, anti-VM, timing checks, obfuscation and how analysts defeat them."),
            ("malware-families", "Tracking Malware Families", "advanced", 8,
             "Code similarity, config extraction, clustering and attribution caveats."),
        ],
    },
    {
        "id": "09-secure-development",
        "title": "Secure Development",
        "desc": "Building security into the software lifecycle: modelling threats, writing safe code and "
                "automating verification in the pipeline.",
        "chapters": [
            ("secure-sdlc", "Secure SDLC", "beginner", 8,
             "Shifting left, security activities per phase, gates and maturity models (BSIMM/SAMM)."),
            ("threat-modeling", "Threat Modeling", "intermediate", 10,
             "STRIDE, attack trees, data-flow diagrams, PASTA and turning models into requirements."),
            ("secure-coding", "Secure Coding", "intermediate", 12,
             "Input validation, output encoding, safe APIs and language-specific pitfalls."),
            ("devsecops", "DevSecOps", "intermediate", 10,
             "Pipeline security, policy as code, guardrails and measuring program effectiveness."),
            ("sast", "Static Application Security Testing", "intermediate", 8,
             "How SAST works, taint analysis, rule tuning, triage and CI integration."),
            ("dast", "Dynamic Application Security Testing", "intermediate", 8,
             "Crawling, active scanning, authenticated scans and pipeline gating."),
            ("iast", "Interactive Application Security Testing", "intermediate", 6,
             "Instrumentation, runtime coverage, and the trade-offs versus SAST and DAST."),
            ("secrets-management", "Secrets Management", "intermediate", 8,
             "Vaulting, dynamic secrets, rotation, detection of leaks and preventing hardcoded keys."),
            ("cicd-security", "CI/CD Security", "advanced", 10,
             "Runner isolation, poisoned pipeline execution, artefact integrity and OIDC federation."),
            ("dependency-security", "Dependency Security", "intermediate", 8,
             "SCA, transitive risk, lockfiles, pinning and vulnerability triage for third-party code."),
            ("supply-chain-security", "Software Supply Chain Security", "advanced", 10,
             "SLSA, provenance, signing with Sigstore, build integrity and threat scenarios."),
            ("sbom", "Software Bill of Materials", "intermediate", 6,
             "SPDX and CycloneDX, generation, consumption, VEX and continuous monitoring."),
            ("api-secure-design", "Secure API Design", "intermediate", 8,
             "AuthN/AuthZ patterns, input contracts, rate limiting and secure defaults."),
            ("secure-defaults", "Secure Defaults and Hardening", "intermediate", 6,
             "Least privilege, fail-safe design, configuration baselines and secure-by-design principles."),
            ("code-review-security", "Security Code Review", "advanced", 10,
             "Manual review methodology, sink hunting, diff review and reviewer tooling."),
        ],
    },
    {
        "id": "10-cloud-security",
        "title": "Cloud Security",
        "desc": "Provider-specific and provider-agnostic security for modern cloud-native systems.",
        "chapters": [
            ("cloud-security-fundamentals", "Cloud Security Fundamentals", "beginner", 8,
             "Shared responsibility, cloud-native threat models, the control plane and blast radius."),
            ("aws-security", "AWS Security", "intermediate", 16,
             "IAM, organisations, VPC, GuardDuty, S3 exposure and common AWS attack paths."),
            ("azure-security", "Azure Security", "intermediate", 14,
             "Entra ID, RBAC, management groups, Defender and Azure-specific privilege escalation."),
            ("gcp-security", "GCP Security", "intermediate", 12,
             "IAM, org policy, service accounts, VPC-SC and GCP privilege-escalation chains."),
            ("cloud-iam", "Cloud Identity and Access Management", "advanced", 12,
             "Policy evaluation, trust relationships, privilege escalation and least-privilege design."),
            ("cloud-networking-security", "Cloud Networking Security", "intermediate", 8,
             "VPCs, security groups, private endpoints, egress control and network segmentation."),
            ("cloud-container-security", "Cloud Container and Registry Security", "advanced", 10,
             "Managed Kubernetes, registry trust, IRSA/workload identity and runtime protection."),
            ("cloud-kubernetes-security", "Managed Kubernetes Security", "advanced", 12,
             "EKS/AKS/GKE hardening, node identity, admission control and multi-tenant isolation."),
            ("iac-security", "Infrastructure as Code Security", "intermediate", 10,
             "Terraform/CloudFormation scanning, drift, module trust and policy as code."),
            ("cspm", "Cloud Security Posture Management", "intermediate", 8,
             "Misconfiguration detection, benchmarks, guardrails and remediation automation."),
            ("cloud-detection", "Cloud Detection and Monitoring", "advanced", 12,
             "CloudTrail/Activity logs, threat detection services and cloud-native SIEM."),
            ("cloud-incident-response", "Cloud Incident Response", "advanced", 12,
             "Cloud evidence acquisition, containment via API, credential invalidation and forensics."),
            ("serverless-cloud-security", "Serverless and PaaS Security", "intermediate", 8,
             "Function isolation, event-source trust, secrets and cold-path telemetry gaps."),
            ("multicloud-security", "Multi-Cloud and Hybrid Security", "advanced", 8,
             "Identity federation, consistent policy, cross-cloud blast radius and tooling."),
        ],
    },
    {
        "id": "11-wireless",
        "title": "Wireless and RF Security",
        "desc": "Security of radio-based protocols from Wi-Fi to cellular, tested against lab hardware only.",
        "chapters": [
            ("rf-fundamentals", "RF and Wireless Fundamentals", "beginner", 8,
             "Spectrum, modulation, antennas, SDR basics and the shared-medium threat model."),
            ("wifi", "Wi-Fi Security", "intermediate", 14,
             "802.11 frames, WEP/WPA/WPA2/WPA3, 4-way handshake, PMKID and enterprise EAP."),
            ("bluetooth", "Bluetooth and BLE Security", "intermediate", 10,
             "Pairing, GATT, BLE sniffing, spoofing and vulnerabilities like KNOB and BlueBorne."),
            ("rfid", "RFID Security", "intermediate", 8,
             "LF/HF tags, MIFARE, cloning, relay attacks and access-control bypass in a lab."),
            ("nfc", "NFC Security", "intermediate", 6,
             "NDEF, card emulation, relay and replay, and mobile-wallet threat models."),
            ("zigbee", "Zigbee and 802.15.4", "advanced", 8,
             "Mesh networking, key provisioning, sniffing and smart-home attack surface."),
            ("lora", "LoRa and LoRaWAN", "advanced", 8,
             "Long-range IoT, join procedures, key management and replay/jamming risks."),
            ("cellular", "Cellular Security (4G/5G)", "advanced", 10,
             "Air interface, IMSI catchers, roaming/SS7 risks and the 5G security architecture."),
            ("sdr", "Software Defined Radio", "advanced", 10,
             "GNU Radio, capture/replay, signal identification and lawful experimentation."),
            ("gps", "GPS and GNSS Security", "advanced", 6,
             "Positioning basics, spoofing, jamming and resilient-timing considerations."),
        ],
    },
    {
        "id": "12-identity",
        "title": "Identity and Access",
        "desc": "The directory, authentication and federation systems that attackers target to own everything.",
        "chapters": [
            ("identity-fundamentals", "Identity Fundamentals", "beginner", 8,
             "Identification, authentication, authorization, accounting and identity lifecycle."),
            ("active-directory", "Active Directory", "advanced", 16,
             "Forests, domains, trusts, GPOs, the schema and the objects attackers pivot through."),
            ("azure-ad", "Entra ID (Azure AD)", "advanced", 12,
             "Tenants, conditional access, app registrations, tokens and cloud-identity attacks."),
            ("ldap-identity", "LDAP as an Identity Store", "intermediate", 6,
             "Schema, binds, group membership and query-driven enumeration."),
            ("kerberos-identity", "Kerberos in Depth", "expert", 14,
             "Tickets, PAC, S4U delegation, encryption types and the full ticket-attack catalogue."),
            ("ntlm", "NTLM", "advanced", 10,
             "Challenge/response, pass-the-hash, relay, coercion and why NTLM persists."),
            ("sso", "Single Sign-On", "intermediate", 8,
             "Federation patterns, SAML/OIDC trade-offs, session risks and IdP compromise impact."),
            ("mfa", "Multi-Factor Authentication", "intermediate", 8,
             "Factors, TOTP/push/WebAuthn, MFA fatigue, bypasses and phishing-resistant design."),
            ("passwordless", "Passwordless and FIDO2", "intermediate", 6,
             "WebAuthn ceremonies, passkeys, attestation and enterprise rollout."),
            ("pam", "Privileged Access Management", "advanced", 8,
             "Tiering, just-in-time access, vaulting, session recording and break-glass."),
            ("identity-governance", "Identity Governance", "intermediate", 6,
             "Joiner/mover/leaver, access reviews, entitlement creep and least privilege at scale."),
        ],
    },
    {
        "id": "13-digital-forensics",
        "title": "Digital Forensics and Incident Response",
        "desc": "Evidence-driven investigation across memory, disk, network and cloud, kept forensically sound.",
        "chapters": [
            ("dfir-fundamentals", "DFIR Fundamentals", "beginner", 8,
             "Forensic principles, order of volatility, chain of custody and legal admissibility."),
            ("memory-forensics-deep", "Memory Forensics in Depth", "advanced", 14,
             "Acquisition, structures, plugins, rootkit hunting and reconstructing execution."),
            ("disk-forensics-deep", "Disk Forensics in Depth", "advanced", 14,
             "NTFS/ext4/APFS internals, journaling, carving, and building a super timeline."),
            ("browser-forensics", "Browser Forensics", "intermediate", 8,
             "History, cache, cookies, storage, downloads and reconstructing user activity."),
            ("cloud-forensics", "Cloud Forensics", "advanced", 10,
             "Log-centric investigation, API-based acquisition and the limits of cloud evidence."),
            ("email-forensics", "Email Forensics", "intermediate", 6,
             "Header analysis, transport reconstruction, mailbox artefacts and BEC investigation."),
            ("log-forensics", "Log Forensics", "intermediate", 8,
             "Windows event logs, Linux logs, correlation and detecting anti-forensics."),
            ("timeline-analysis", "Timeline Analysis", "advanced", 10,
             "Super timelines with plaso, pivoting, anchor events and narrative reconstruction."),
            ("mobile-forensics", "Mobile Forensics", "advanced", 10,
             "Acquisition tiers, app data, secure enclaves and the constraints of modern devices."),
            ("anti-forensics", "Anti-Forensics", "advanced", 6,
             "Timestomping, log clearing, wiping, and how investigators detect tampering."),
            ("malware-forensics", "Malware-Focused Forensics", "advanced", 8,
             "Finding, extracting and triaging malicious artefacts during an investigation."),
            ("forensic-reporting", "Forensic Reporting", "intermediate", 6,
             "Findings documentation, defensibility, expert-witness basics and executive summaries."),
        ],
    },
    {
        "id": "14-threat-intelligence",
        "title": "Threat Intelligence and Frameworks",
        "desc": "The shared vocabularies, catalogues and scoring systems that connect every other domain.",
        "chapters": [
            ("cti-fundamentals", "Cyber Threat Intelligence Fundamentals", "beginner", 8,
             "The intel lifecycle, requirements, collection, analysis and dissemination."),
            ("mitre-attack", "MITRE ATT&CK", "intermediate", 12,
             "Tactics, techniques, sub-techniques, matrices, and using ATT&CK to drive detection."),
            ("attack-navigator", "ATT&CK Navigator", "intermediate", 4,
             "Building layers, heatmaps, coverage mapping and gap analysis."),
            ("d3fend", "MITRE D3FEND and Engage", "intermediate", 4,
             "Countermeasure knowledge graph, mapping defences and adversary engagement."),
            ("capec", "CAPEC", "intermediate", 6,
             "Attack pattern catalogue, relationships to CWE and using CAPEC in threat models."),
            ("cwe", "CWE", "intermediate", 6,
             "Weakness taxonomy, views, relationships and mapping findings correctly."),
            ("cve", "CVE", "beginner", 5,
             "Identifiers, the CNA ecosystem, records, and using CVEs responsibly."),
            ("cvss", "CVSS", "beginner", 6,
             "Base/temporal/environmental metrics, v3.1 vs v4.0 and scoring pitfalls."),
            ("epss", "EPSS", "beginner", 4,
             "Exploit prediction scoring, interpretation and combining EPSS with CVSS and KEV."),
            ("kev", "CISA KEV and Prioritisation", "beginner", 4,
             "Known-exploited-vulnerability catalogue and risk-based patch prioritisation."),
            ("osint-intelligence", "OSINT for Intelligence", "intermediate", 8,
             "Collection tradecraft, verification, source reliability and analytic bias."),
            ("ioc-ioa", "Indicators: IOC and IOA", "intermediate", 6,
             "Atomic/computed/behavioural indicators, the pyramid of pain and indicator decay."),
            ("ttp-analysis", "TTP Analysis", "advanced", 8,
             "Behaviour-centric analysis, ATT&CK mapping and building adversary profiles."),
            ("diamond-model", "The Diamond Model and Kill Chains", "intermediate", 6,
             "Adversary/infrastructure/capability/victim, kill chains and unified frameworks."),
            ("threat-intel-platforms", "Threat Intelligence Platforms and Sharing", "intermediate", 6,
             "MISP, STIX/TAXII, TLP, feeds and operationalising shared intelligence."),
            ("attribution", "Attribution", "advanced", 6,
             "Evidence, confidence, false flags and the limits of attribution."),
        ],
    },
    {
        "id": "15-compliance",
        "title": "Governance, Risk and Compliance",
        "desc": "The frameworks, laws and risk methods that turn security work into an accountable program.",
        "chapters": [
            ("grc-fundamentals", "GRC Fundamentals", "beginner", 8,
             "Governance, risk management, compliance, the CIA triad and control types."),
            ("risk-management", "Risk Management", "intermediate", 10,
             "Risk identification, qualitative/quantitative analysis, FAIR, treatment and acceptance."),
            ("nist-csf", "NIST Cybersecurity Framework", "beginner", 6,
             "Govern/Identify/Protect/Detect/Respond/Recover, tiers, profiles and CSF 2.0."),
            ("nist-800-53", "NIST SP 800-53", "intermediate", 8,
             "Control families, baselines, tailoring and using 800-53 as a control catalogue."),
            ("nist-800-171", "NIST SP 800-171 and CMMC", "intermediate", 6,
             "Protecting CUI, control mapping and the CMMC assessment model."),
            ("nist-rmf", "NIST Risk Management Framework", "intermediate", 6,
             "Categorise, select, implement, assess, authorise, monitor and ATO."),
            ("iso-27001", "ISO/IEC 27001 and 27002", "intermediate", 8,
             "ISMS, Annex A controls, Statement of Applicability and certification."),
            ("pci-dss", "PCI DSS", "intermediate", 8,
             "Cardholder data environment, the twelve requirements, scoping and v4.0 changes."),
            ("soc2", "SOC 2", "intermediate", 6,
             "Trust services criteria, Type I vs II, evidence and the audit process."),
            ("gdpr", "GDPR", "beginner", 6,
             "Lawful bases, data-subject rights, breach notification and privacy by design."),
            ("hipaa", "HIPAA", "beginner", 6,
             "Privacy and Security Rules, safeguards, PHI and breach handling."),
            ("privacy-engineering", "Privacy Engineering", "intermediate", 6,
             "Data minimisation, PETs, DPIAs and building privacy into systems."),
            ("security-policy", "Security Policy and Standards", "beginner", 6,
             "Policy hierarchy, writing enforceable standards and exception handling."),
            ("audit-assurance", "Audit and Assurance", "intermediate", 6,
             "Control testing, evidence, sampling, findings and continuous compliance."),
            ("security-awareness", "Security Awareness and Culture", "beginner", 4,
             "Behaviour change, phishing simulation ethics and measuring program impact."),
            ("business-continuity", "Business Continuity and Disaster Recovery", "intermediate", 6,
             "BIA, RTO/RPO, backup strategy, resilience and testing recovery plans."),
        ],
    },
]
