# -*- coding: utf-8 -*-
# Cybersecurity-Mastery - an interactive, offline cybersecurity learning app.
# Copyright (C) 2026 Nithees Narendra S
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of Cybersecurity-Mastery. It is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. There is NO WARRANTY. See the
# LICENSE file for the full text. For use outside the GPL-3.0 terms (e.g.
# proprietary/commercial), contact the copyright holder for a separate licence.

"""Topic manifest, part 1: sections 00-05 (foundations through vulnerabilities).

Chapter tuple layout:
    (slug, title, difficulty, hours, abstract)

difficulty: beginner | intermediate | advanced | expert
hours:      estimated study time, including labs
abstract:   one-line description used in indexes, SUMMARY files and search
"""

SECTIONS = [
    {
        "id": "00-foundations",
        "title": "Foundations",
        "desc": "The computer science, systems and programming groundwork every "
                "security discipline is built on. Start here if anything below feels shaky.",
        "chapters": [
            ("computer-science", "Computer Science Fundamentals", "beginner", 6,
             "Computation, abstraction, complexity and the models that underpin every security tool."),
            ("programming", "Programming Fundamentals", "beginner", 10,
             "Variables, control flow, functions, types and memory as they matter to security work."),
            ("algorithms", "Algorithms", "intermediate", 12,
             "Sorting, searching, graph traversal and the complexity analysis behind scanner and cracker design."),
            ("data-structures", "Data Structures", "intermediate", 12,
             "Arrays, lists, trees, hash tables and tries, plus how their layout creates memory-safety bugs."),
            ("discrete-mathematics", "Discrete Mathematics", "intermediate", 10,
             "Logic, sets, combinatorics, number theory and probability, the mathematical base of cryptography."),
            ("computer-architecture", "Computer Architecture", "intermediate", 12,
             "CPU pipelines, registers, cache, MMU and privilege rings, the substrate exploits actually target."),
            ("operating-systems", "Operating Systems", "intermediate", 14,
             "Processes, threads, scheduling, virtual memory, syscalls and the kernel/user boundary."),
            ("networking-primer", "Networking Primer", "beginner", 8,
             "A fast, practical on-ramp to packets, addressing and protocol layering before the deep dive."),
            ("databases", "Databases", "intermediate", 10,
             "Relational and NoSQL engines, SQL semantics, transactions and where injection actually happens."),
            ("virtualization", "Virtualization", "intermediate", 8,
             "Hypervisor types, hardware-assisted virtualization, snapshots and lab isolation guarantees."),
            ("containers", "Containers", "intermediate", 8,
             "Namespaces, cgroups, union filesystems and why a container is not a security boundary by default."),
            ("cloud", "Cloud Computing", "intermediate", 8,
             "Service models, the shared responsibility model, regions, tenancy and cloud control planes."),
            ("linux", "Linux", "beginner", 14,
             "Filesystem hierarchy, permissions, processes, systemd, package management and the shell."),
            ("windows", "Windows", "beginner", 14,
             "NT architecture, registry, services, tokens, SIDs, ACLs and the Windows API surface."),
            ("powershell", "PowerShell", "intermediate", 10,
             "Objects in the pipeline, remoting, execution policy, logging and offensive/defensive tradecraft."),
            ("bash", "Bash and POSIX Shell", "beginner", 8,
             "Redirection, pipelines, quoting, job control and safe scripting patterns for security automation."),
            ("python", "Python", "beginner", 16,
             "The default language of security tooling: sockets, requests, parsing, automation and packaging."),
            ("c", "C", "advanced", 16,
             "Pointers, manual memory management and undefined behaviour, the source of most memory-corruption CVEs."),
            ("cpp", "C++", "advanced", 14,
             "Objects, vtables, RAII, templates and the exploitation surface unique to C++ binaries."),
            ("rust", "Rust", "advanced", 14,
             "Ownership, borrowing and lifetimes as a compile-time defence against memory-safety vulnerabilities."),
            ("go", "Go", "intermediate", 12,
             "Goroutines, channels, static binaries and why Go dominates modern offensive and cloud tooling."),
            ("javascript", "JavaScript", "intermediate", 12,
             "The event loop, prototypes, the DOM and the execution context that XSS lives inside."),
            ("assembly", "Assembly Language", "advanced", 18,
             "x86-64 and ARM64 instruction sets, calling conventions and stack frames for reversing and exploitation."),
            ("git", "Git", "beginner", 6,
             "Objects, refs, branching, history rewriting and how secrets leak through commit history."),
            ("github", "GitHub and Forge Security", "beginner", 5,
             "Pull requests, Actions, tokens, branch protection and the supply-chain risks of a shared forge."),
        ],
    },
    {
        "id": "01-networking",
        "title": "Networking",
        "desc": "Protocol-by-protocol internals, on the wire. Every attack and every detection "
                "eventually reduces to bytes crossing a link.",
        "chapters": [
            ("osi-model", "The OSI Model", "beginner", 3,
             "Seven-layer reference model, what each layer really owns and how to use it as a triage tool."),
            ("tcp-ip", "TCP/IP", "beginner", 8,
             "The DoD model, IP datagrams, TCP state machine, UDP, ports, MTU and fragmentation."),
            ("routing", "Routing", "intermediate", 8,
             "Longest-prefix match, static vs dynamic routing, RIP/OSPF/EIGRP and route-based attacks."),
            ("switching", "Switching", "intermediate", 6,
             "MAC learning, VLANs, trunking, STP and layer-2 attacks such as VLAN hopping and STP takeover."),
            ("arp", "ARP", "beginner", 4,
             "Address resolution, the ARP cache, gratuitous ARP and the mechanics of ARP spoofing."),
            ("dhcp", "DHCP", "beginner", 4,
             "DORA exchange, options, relays, rogue servers, starvation attacks and DHCP snooping."),
            ("dns", "DNS", "intermediate", 10,
             "Resolution flow, record types, zone transfers, DNSSEC, DoH/DoT, tunnelling and cache poisoning."),
            ("icmp", "ICMP", "beginner", 3,
             "Message types, path MTU discovery, traceroute mechanics and ICMP covert channels."),
            ("http", "HTTP", "beginner", 8,
             "Request/response grammar, methods, status codes, headers, HTTP/1.1 vs /2 vs /3 framing."),
            ("https", "HTTPS", "intermediate", 5,
             "HTTP over TLS, SNI, ALPN, HSTS, mixed content and interception proxies."),
            ("tls", "TLS", "advanced", 12,
             "Handshake internals for TLS 1.2 and 1.3, cipher suites, session resumption and downgrade attacks."),
            ("ssh", "SSH", "intermediate", 8,
             "Transport, auth and connection layers, host keys, agent forwarding, tunnels and key hygiene."),
            ("smtp", "SMTP and Email Transport", "intermediate", 8,
             "Envelope vs headers, relaying, SPF, DKIM, DMARC, MTA-STS and spoofing mechanics."),
            ("ftp", "FTP and File Transfer", "beginner", 4,
             "Active vs passive mode, control/data channels, anonymous access, FTPS and SFTP contrasted."),
            ("smb", "SMB", "intermediate", 10,
             "Dialects, session setup, signing, shares, named pipes and the protocol behind lateral movement."),
            ("ldap", "LDAP", "intermediate", 8,
             "Directory model, DNs, filters, binds, LDAPS/StartTLS, injection and enumeration."),
            ("kerberos", "Kerberos", "advanced", 14,
             "AS-REQ through TGS-REP, tickets, PACs, delegation and the full family of ticket attacks."),
            ("bgp", "BGP", "advanced", 10,
             "Path-vector routing, ASNs, peering, route leaks, prefix hijacking, RPKI and internet-scale outages."),
            ("ipv6", "IPv6", "intermediate", 8,
             "Addressing, SLAAC, NDP, extension headers, transition mechanisms and IPv6-only attack paths."),
            ("nat", "NAT", "beginner", 5,
             "SNAT, DNAT, PAT, hairpinning, NAT traversal, STUN/TURN and why NAT is not a firewall."),
            ("firewalls", "Firewalls", "intermediate", 10,
             "Packet filtering, stateful inspection, NGFW, WAF, nftables/pf rulesets and evasion techniques."),
            ("vpn", "VPN", "intermediate", 10,
             "IPsec, WireGuard, OpenVPN, SSL VPNs, split tunnelling and VPN appliance CVEs."),
            ("load-balancers", "Load Balancers and Proxies", "intermediate", 8,
             "L4/L7 balancing, health checks, X-Forwarded-For trust, TLS termination and request smuggling."),
            ("packet-analysis", "Packet Analysis", "intermediate", 12,
             "Capture, filter, follow and interpret traffic with tcpdump, Wireshark and tshark."),
            ("protocol-internals", "Protocol Internals and Reverse Engineering", "advanced", 12,
             "Dissecting undocumented and binary protocols, building dissectors and fuzzing parsers."),
        ],
    },
    {
        "id": "02-cryptography",
        "title": "Cryptography",
        "desc": "Primitives, protocols and the failure modes that turn strong maths into broken systems.",
        "chapters": [
            ("cryptography-foundations", "Cryptography Foundations", "beginner", 6,
             "Confidentiality, integrity, authenticity, threat models, Kerckhoffs's principle and entropy."),
            ("symmetric", "Symmetric Cryptography", "intermediate", 10,
             "Block and stream ciphers, modes of operation, padding, IV/nonce handling and AEAD."),
            ("asymmetric", "Asymmetric Cryptography", "intermediate", 10,
             "Trapdoor functions, key pairs, hybrid encryption and the maths behind public-key systems."),
            ("aes", "AES", "intermediate", 8,
             "Rijndael internals, key schedule, rounds, GCM/CBC/CTR modes and practical misuse."),
            ("rsa", "RSA", "advanced", 10,
             "Key generation, padding schemes, common implementation attacks and CTF-style factorisation."),
            ("ecc", "Elliptic Curve Cryptography", "advanced", 10,
             "Curve arithmetic, ECDSA, EdDSA, X25519 and nonce-reuse key recovery."),
            ("diffie-hellman", "Diffie-Hellman", "intermediate", 6,
             "Key agreement, ephemeral vs static, forward secrecy, small-subgroup and Logjam attacks."),
            ("hashes", "Hash Functions", "beginner", 6,
             "Preimage and collision resistance, MD5/SHA families, BLAKE3 and length-extension."),
            ("mac", "Message Authentication Codes", "intermediate", 5,
             "MAC goals, CBC-MAC, CMAC, Poly1305 and encrypt-then-MAC composition rules."),
            ("hmac", "HMAC", "intermediate", 4,
             "Construction, security proof intuition, key sizing and constant-time verification."),
            ("digital-signatures", "Digital Signatures", "intermediate", 8,
             "Signature schemes, non-repudiation, signing vs encryption and signature-verification bypasses."),
            ("certificates", "X.509 Certificates", "intermediate", 8,
             "Fields, extensions, chains, SANs, revocation, CT logs and validation mistakes."),
            ("pki", "Public Key Infrastructure", "advanced", 10,
             "CAs, RAs, trust stores, enrolment, internal PKI design and AD CS abuse paths."),
            ("tls-cryptography", "TLS Cryptography", "advanced", 8,
             "How the primitives compose inside TLS, key schedules, 0-RTT risks and protocol attacks."),
            ("password-storage", "Password Hashing and Storage", "intermediate", 6,
             "bcrypt, scrypt, Argon2, salting, peppering, work factors and credential-stuffing economics."),
            ("randomness", "Randomness and Key Management", "advanced", 8,
             "CSPRNGs, entropy sources, key rotation, HSMs, KMS design and key-compromise recovery."),
            ("post-quantum", "Post-Quantum Cryptography", "advanced", 8,
             "Shor and Grover impact, ML-KEM/ML-DSA, hybrid deployment and harvest-now-decrypt-later."),
            ("cryptanalysis", "Applied Cryptanalysis", "expert", 12,
             "Padding oracles, timing side channels, bit-flipping, nonce reuse and hash-length extension in practice."),
        ],
    },
    {
        "id": "03-web-security",
        "title": "Web Security",
        "desc": "How the web platform works, how its trust boundaries are drawn, and where they leak.",
        "chapters": [
            ("web-architecture", "Web Application Architecture", "beginner", 6,
             "Clients, servers, reverse proxies, APIs, SPAs, rendering models and where controls belong."),
            ("http-protocol", "HTTP for Security Testing", "beginner", 8,
             "Method semantics, header trust, caching, redirects, parsers and desync-prone constructs."),
            ("cookies", "Cookies", "beginner", 6,
             "Attributes, scope, SameSite, prefixes, partitioning and cookie tossing/injection."),
            ("sessions", "Session Management", "intermediate", 8,
             "Session identifiers, fixation, invalidation, server vs stateless sessions and concurrency."),
            ("authentication", "Web Authentication", "intermediate", 10,
             "Password flows, MFA, WebAuthn/passkeys, magic links, rate limiting and account recovery abuse."),
            ("authorization", "Authorization", "intermediate", 10,
             "RBAC, ABAC, ReBAC, policy engines, multi-tenancy and the roots of broken access control."),
            ("jwt", "JSON Web Tokens", "intermediate", 8,
             "JWS/JWE structure, alg confusion, kid injection, claims validation and revocation strategy."),
            ("oauth", "OAuth 2.0 and 2.1", "advanced", 12,
             "Grant types, PKCE, redirect URI validation, token leakage and confused-deputy attacks."),
            ("openid-connect", "OpenID Connect", "advanced", 8,
             "ID tokens, discovery, nonce/state, hybrid flow risks and identity-provider mix-up attacks."),
            ("saml", "SAML", "advanced", 10,
             "Assertions, bindings, signature wrapping, XSW attacks and canonicalisation pitfalls."),
            ("owasp-top-10", "OWASP Top 10", "beginner", 10,
             "The 2021 categories mapped to concrete bug classes, tests and remediations."),
            ("api-security", "API Security", "intermediate", 12,
             "REST design flaws, OWASP API Top 10, mass assignment, BOLA/BFLA and gateway controls."),
            ("graphql", "GraphQL Security", "advanced", 8,
             "Introspection, query depth/complexity abuse, batching attacks and resolver-level authorization."),
            ("websockets", "WebSockets", "intermediate", 6,
             "Upgrade handshake, origin checks, CSWSH, message-level authorization and proxying."),
            ("cors", "CORS", "intermediate", 6,
             "Preflights, credentialed requests, reflected origins, null origin and misconfiguration impact."),
            ("csp", "Content Security Policy", "advanced", 8,
             "Directives, nonces, strict-dynamic, common bypasses and rollout with report-only."),
            ("browser-security-model", "Browser Security Model", "intermediate", 10,
             "Same-origin policy, site isolation, sandboxing, storage partitioning and security headers."),
            ("file-upload-security", "File Upload Security", "intermediate", 6,
             "Content-type and extension validation, path handling, image parsers and storage isolation."),
            ("client-side-security", "Client-Side Security", "advanced", 10,
             "DOM clobbering, prototype pollution, postMessage, clickjacking and supply-chain scripts."),
            ("web-cache-security", "Web Cache Poisoning and Deception", "advanced", 8,
             "Cache keys, unkeyed input, poisoning primitives, deception and CDN-level defences."),
            ("request-smuggling", "HTTP Request Smuggling", "expert", 10,
             "CL.TE, TE.CL, TE.TE, H2 downgrade desync, discovery methodology and exploitation impact."),
        ],
    },
    {
        "id": "04-vulnerabilities",
        "title": "Vulnerabilities",
        "desc": "Bug classes from first principles: root cause, exploitation, detection and durable fixes. "
                "Each chapter maps to CWE, CAPEC, OWASP and real CVEs.",
        "chapters": [
            ("vulnerability-taxonomy", "Vulnerability Taxonomy", "beginner", 5,
             "How CWE, CAPEC, OWASP and ATT&CK relate, and how to classify a finding correctly."),
            ("sql-injection", "SQL Injection", "intermediate", 12,
             "Query context, union and error-based extraction, stacked queries and parameterised defences."),
            ("blind-sql-injection", "Blind SQL Injection", "advanced", 10,
             "Boolean, time-based and out-of-band inference, plus automation and WAF-aware tuning."),
            ("nosql-injection", "NoSQL Injection", "intermediate", 6,
             "Operator injection, type juggling in document stores and server-side JavaScript execution."),
            ("xss", "Cross-Site Scripting", "intermediate", 12,
             "Reflected, stored and DOM sinks, contexts, encoding rules and the modern XSS defence stack."),
            ("stored-xss", "Stored XSS", "intermediate", 6,
             "Persistence paths, admin-panel escalation, sanitiser bypasses and worm behaviour."),
            ("dom-xss", "DOM-Based XSS", "advanced", 8,
             "Source-to-sink dataflow, client-side templating, Trusted Types and DOM Invader workflow."),
            ("csrf", "Cross-Site Request Forgery", "intermediate", 8,
             "State-changing requests, token patterns, SameSite behaviour and CSRF-in-JSON edge cases."),
            ("ssrf", "Server-Side Request Forgery", "advanced", 12,
             "URL parsing, cloud metadata theft, blind SSRF, DNS rebinding and egress-control defences."),
            ("rce", "Remote Code Execution", "advanced", 12,
             "How arbitrary code execution is reached, chained and stabilised, plus containment strategies."),
            ("lfi", "Local File Inclusion", "intermediate", 8,
             "Include semantics, wrappers, log poisoning, session-file abuse and LFI-to-RCE chains."),
            ("rfi", "Remote File Inclusion", "intermediate", 5,
             "Remote include conditions, language configuration and hosting payloads safely in a lab."),
            ("directory-traversal", "Directory Traversal", "beginner", 6,
             "Path canonicalisation, encoding tricks, chroot/jail limits and safe file-access patterns."),
            ("xxe", "XML External Entity Injection", "advanced", 8,
             "DTDs, entity expansion, blind OOB exfiltration, SSRF pivots and parser hardening."),
            ("command-injection", "OS Command Injection", "intermediate", 8,
             "Shell metacharacters, argument injection, blind detection and safe process invocation."),
            ("template-injection", "Server-Side Template Injection", "advanced", 10,
             "Engine fingerprinting, sandbox escapes in Jinja2/Twig/Freemarker and template-to-RCE chains."),
            ("insecure-deserialization", "Insecure Deserialization", "expert", 12,
             "Object graphs, gadget chains in Java/.NET/PHP/Python and format-level mitigations."),
            ("idor", "Insecure Direct Object References", "beginner", 6,
             "Object-level authorization, identifier enumeration, tenant isolation and systematic testing."),
            ("race-conditions", "Race Conditions", "advanced", 10,
             "TOCTOU, limit-overrun, single-packet attacks and locking or idempotency defences."),
            ("memory-corruption", "Memory Corruption", "expert", 12,
             "Memory layout, corruption primitives, exploit mitigations and the modern exploitation pipeline."),
            ("buffer-overflow", "Buffer Overflows", "advanced", 12,
             "Bounds-check failures, overwrite targets, shellcode and mitigation-aware exploitation."),
            ("stack-overflow", "Stack-Based Overflows", "advanced", 12,
             "Saved return addresses, canaries, ASLR/DEP, ROP chains and a full local lab exploit."),
            ("heap-overflow", "Heap-Based Overflows", "expert", 14,
             "Allocator internals, chunk metadata, use-after-free, tcache poisoning and heap grooming."),
            ("integer-overflow", "Integer Overflows", "advanced", 8,
             "Wrap-around, truncation, signedness confusion and the allocation bugs they cause."),
            ("format-strings", "Format String Vulnerabilities", "advanced", 8,
             "Varargs abuse, %n writes, memory disclosure and arbitrary-write exploitation."),
            ("authentication-bypass", "Authentication Bypass", "intermediate", 8,
             "Logic gaps, forced browsing, token forgery, response tampering and 2FA bypass patterns."),
            ("business-logic", "Business Logic Vulnerabilities", "advanced", 10,
             "Workflow abuse, price and quantity manipulation, state machines and non-scannable bugs."),
            ("privilege-escalation-concepts", "Privilege Escalation Concepts", "intermediate", 8,
             "Vertical vs horizontal escalation, trust boundaries and escalation primitives across platforms."),
            ("cwe-top-25", "CWE Top 25 Reference", "intermediate", 10,
             "Every entry in the CWE Top 25 with root cause, example, detection and fix."),
            ("supply-chain-vulnerabilities", "Dependency and Supply Chain Vulnerabilities", "advanced", 8,
             "Typosquatting, dependency confusion, build compromise and reproducible-build defences."),
        ],
    },
    {
        "id": "05-platforms",
        "title": "Platforms",
        "desc": "Security architecture, attack surface and hardening for each major platform family.",
        "chapters": [
            ("linux-security", "Linux Security", "intermediate", 14,
             "DAC, capabilities, SELinux/AppArmor, namespaces, auditd and privilege-escalation surface."),
            ("windows-security", "Windows Security", "intermediate", 16,
             "Tokens, integrity levels, UAC, LSASS, WDAC, Credential Guard and event-log telemetry."),
            ("macos-security", "macOS Security", "advanced", 10,
             "SIP, TCC, Gatekeeper, notarisation, XPC, keychain and macOS persistence locations."),
            ("android-security", "Android Security", "advanced", 12,
             "Sandbox model, permissions, APK internals, root detection and mobile testing methodology."),
            ("ios-security", "iOS Security", "advanced", 12,
             "Secure Boot chain, Data Protection, entitlements, jailbreak impact and IPA analysis."),
            ("embedded-security", "Embedded Systems Security", "advanced", 12,
             "Firmware extraction, UART/JTAG, bootloaders, secure boot and hardware attack surface."),
            ("iot-security", "IoT Security", "advanced", 12,
             "Device lifecycle, cloud/companion apps, MQTT/CoAP, update integrity and IoT botnet history."),
            ("ics-security", "ICS Security", "advanced", 12,
             "Process control, PLCs, safety instrumented systems and the Purdue reference architecture."),
            ("scada-security", "SCADA Security", "advanced", 10,
             "Modbus, DNP3, S7comm, historian exposure and monitoring OT networks passively."),
            ("cloud-platform-security", "Cloud Platform Security", "intermediate", 12,
             "Control vs data plane, metadata services, tenancy and cross-account trust failures."),
            ("container-security", "Container Security", "advanced", 12,
             "Image provenance, runtime isolation, seccomp/AppArmor, escapes and admission control."),
            ("kubernetes-security", "Kubernetes Security", "advanced", 16,
             "RBAC, service accounts, network policy, admission control, etcd exposure and attack paths."),
            ("serverless-security", "Serverless Security", "intermediate", 8,
             "Event-driven trust, function IAM, cold-start telemetry gaps and dependency risk."),
            ("virtualization-security", "Virtualization Security", "advanced", 8,
             "Hypervisor attack surface, VM escapes, nested virtualization and lab isolation design."),
            ("mainframe-security", "Mainframe Security", "expert", 8,
             "z/OS, RACF, TSO/JCL, and why legacy transaction processing still matters to attackers."),
        ],
    },
]
